
name: ValidateQuality

on: pull_request

jobs:
  lint-and-test:
    name: lint-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Lint
      uses: CultureHQ/actions-yarn@master
      with:
        args: lint
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: test
      
